package myspringboot.core.mapper;

import java.util.List;
import myspringboot.core.model.Item;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    @Delete({
        "delete from item",
        "where ITEMID = #{itemid,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    @Insert({
        "insert into item (ITEMID, ITEMNAME, ",
        "SIZE, PRICE)",
        "values (#{itemid,jdbcType=CHAR}, #{itemname,jdbcType=VARCHAR}, ",
        "#{size,jdbcType=CHAR}, #{price,jdbcType=INTEGER})"
    })
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    @Select({
        "select",
        "ITEMID, ITEMNAME, SIZE, PRICE",
        "from item",
        "where ITEMID = #{itemid,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="ITEMID", property="itemid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ITEMNAME", property="itemname", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIZE", property="size", jdbcType=JdbcType.CHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER)
    })
    Item selectByPrimaryKey(String itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    @Select({
        "select",
        "ITEMID, ITEMNAME, SIZE, PRICE",
        "from item"
    })
    @Results({
        @Result(column="ITEMID", property="itemid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ITEMNAME", property="itemname", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIZE", property="size", jdbcType=JdbcType.CHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.INTEGER)
    })
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    @Update({
        "update item",
        "set ITEMNAME = #{itemname,jdbcType=VARCHAR},",
          "SIZE = #{size,jdbcType=CHAR},",
          "PRICE = #{price,jdbcType=INTEGER}",
        "where ITEMID = #{itemid,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Item record);
}