package myspringboot.core.mapper;

import java.util.List;
import myspringboot.core.model.Orderdetail;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface OrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.orderdetail
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    @Delete({
        "delete from dbo.orderdetail",
        "where NO = #{no,jdbcType=BIGINT}",
          "and CUSTID = #{custid,jdbcType=INTEGER}",
          "and ITEMID = #{itemid,jdbcType=CHAR}",
          "and TAXID = #{taxid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("no") Long no, @Param("custid") Integer custid, @Param("itemid") String itemid, @Param("taxid") Integer taxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.orderdetail
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    @Insert({
        "insert into dbo.orderdetail (NO, CUSTID, ",
        "ITEMID, TAXID, ORDERDATE, ",
        "QUANTITY, STATUS)",
        "values (#{no,jdbcType=BIGINT}, #{custid,jdbcType=INTEGER}, ",
        "#{itemid,jdbcType=CHAR}, #{taxid,jdbcType=INTEGER}, #{orderdate,jdbcType=DATE}, ",
        "#{quantity,jdbcType=INTEGER}, #{status,jdbcType=INTEGER})"
    })
    int insert(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.orderdetail
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    @Select({
        "select",
        "NO, CUSTID, ITEMID, TAXID, ORDERDATE, QUANTITY, STATUS",
        "from dbo.orderdetail",
        "where NO = #{no,jdbcType=BIGINT}",
          "and CUSTID = #{custid,jdbcType=INTEGER}",
          "and ITEMID = #{itemid,jdbcType=CHAR}",
          "and TAXID = #{taxid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="NO", property="no", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUSTID", property="custid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ITEMID", property="itemid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="TAXID", property="taxid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ORDERDATE", property="orderdate", jdbcType=JdbcType.DATE),
        @Result(column="QUANTITY", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.INTEGER)
    })
    Orderdetail selectByPrimaryKey(@Param("no") Long no, @Param("custid") Integer custid, @Param("itemid") String itemid, @Param("taxid") Integer taxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.orderdetail
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    @Select({
        "select",
        "NO, CUSTID, ITEMID, TAXID, ORDERDATE, QUANTITY, STATUS",
        "from dbo.orderdetail"
    })
    @Results({
        @Result(column="NO", property="no", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CUSTID", property="custid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ITEMID", property="itemid", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="TAXID", property="taxid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ORDERDATE", property="orderdate", jdbcType=JdbcType.DATE),
        @Result(column="QUANTITY", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.INTEGER)
    })
    List<Orderdetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.orderdetail
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    @Update({
        "update dbo.orderdetail",
        "set ORDERDATE = #{orderdate,jdbcType=DATE},",
          "QUANTITY = #{quantity,jdbcType=INTEGER},",
          "STATUS = #{status,jdbcType=INTEGER}",
        "where NO = #{no,jdbcType=BIGINT}",
          "and CUSTID = #{custid,jdbcType=INTEGER}",
          "and ITEMID = #{itemid,jdbcType=CHAR}",
          "and TAXID = #{taxid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Orderdetail record);
}