package myspringboot.core.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.customer.CUSTID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.customer.CUSTNAME
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String custname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.customer.KANA
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String kana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.customer.TEL
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.customer.ADDRESS
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.customer.CUSTID
     *
     * @return the value of dbo.customer.CUSTID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.customer.CUSTID
     *
     * @param custid the value for dbo.customer.CUSTID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.customer.CUSTNAME
     *
     * @return the value of dbo.customer.CUSTNAME
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.customer.CUSTNAME
     *
     * @param custname the value for dbo.customer.CUSTNAME
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setCustname(String custname) {
        this.custname = custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.customer.KANA
     *
     * @return the value of dbo.customer.KANA
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.customer.KANA
     *
     * @param kana the value for dbo.customer.KANA
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setKana(String kana) {
        this.kana = kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.customer.TEL
     *
     * @return the value of dbo.customer.TEL
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.customer.TEL
     *
     * @param tel the value for dbo.customer.TEL
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.customer.ADDRESS
     *
     * @return the value of dbo.customer.ADDRESS
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.customer.ADDRESS
     *
     * @param address the value for dbo.customer.ADDRESS
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }
}