package myspringboot.core.model;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.item.ITEMID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.item.ITEMNAME
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String itemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.item.SIZE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.item.PRICE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.item.ITEMID
     *
     * @return the value of dbo.item.ITEMID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.item.ITEMID
     *
     * @param itemid the value for dbo.item.ITEMID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.item.ITEMNAME
     *
     * @return the value of dbo.item.ITEMNAME
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.item.ITEMNAME
     *
     * @param itemname the value for dbo.item.ITEMNAME
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.item.SIZE
     *
     * @return the value of dbo.item.SIZE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.item.SIZE
     *
     * @param size the value for dbo.item.SIZE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.item.PRICE
     *
     * @return the value of dbo.item.PRICE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.item.PRICE
     *
     * @param price the value for dbo.item.PRICE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}