package myspringboot.core.model;

import java.util.Date;

public class Orderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.NO
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Long no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.CUSTID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.ITEMID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.TAXID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer taxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.ORDERDATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.QUANTITY
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.orderdetail.STATUS
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.NO
     *
     * @return the value of dbo.orderdetail.NO
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Long getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.NO
     *
     * @param no the value for dbo.orderdetail.NO
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setNo(Long no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.CUSTID
     *
     * @return the value of dbo.orderdetail.CUSTID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.CUSTID
     *
     * @param custid the value for dbo.orderdetail.CUSTID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.ITEMID
     *
     * @return the value of dbo.orderdetail.ITEMID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.ITEMID
     *
     * @param itemid the value for dbo.orderdetail.ITEMID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.TAXID
     *
     * @return the value of dbo.orderdetail.TAXID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getTaxid() {
        return taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.TAXID
     *
     * @param taxid the value for dbo.orderdetail.TAXID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setTaxid(Integer taxid) {
        this.taxid = taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.ORDERDATE
     *
     * @return the value of dbo.orderdetail.ORDERDATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.ORDERDATE
     *
     * @param orderdate the value for dbo.orderdetail.ORDERDATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.QUANTITY
     *
     * @return the value of dbo.orderdetail.QUANTITY
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.QUANTITY
     *
     * @param quantity the value for dbo.orderdetail.QUANTITY
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.orderdetail.STATUS
     *
     * @return the value of dbo.orderdetail.STATUS
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.orderdetail.STATUS
     *
     * @param status the value for dbo.orderdetail.STATUS
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}