package myspringboot.core.model;

import java.math.BigDecimal;
import java.util.Date;

public class Tax {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.tax.TAXID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Integer taxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.tax.RATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.tax.ENDDATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    private Date enddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.tax.TAXID
     *
     * @return the value of dbo.tax.TAXID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Integer getTaxid() {
        return taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.tax.TAXID
     *
     * @param taxid the value for dbo.tax.TAXID
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setTaxid(Integer taxid) {
        this.taxid = taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.tax.RATE
     *
     * @return the value of dbo.tax.RATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.tax.RATE
     *
     * @param rate the value for dbo.tax.RATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.tax.ENDDATE
     *
     * @return the value of dbo.tax.ENDDATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.tax.ENDDATE
     *
     * @param enddate the value for dbo.tax.ENDDATE
     *
     * @mbg.generated Sun Jan 26 18:55:42 JST 2020
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
}