package myspringboot.core.model;

import java.util.Date;

public class Tax {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.TAXID
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    private Integer taxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.RATE
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    private Double rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.ENDDATE
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    private Date enddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.TAXID
     *
     * @return the value of tax.TAXID
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    public Integer getTaxid() {
        return taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.TAXID
     *
     * @param taxid the value for tax.TAXID
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    public void setTaxid(Integer taxid) {
        this.taxid = taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.RATE
     *
     * @return the value of tax.RATE
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.RATE
     *
     * @param rate the value for tax.RATE
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.ENDDATE
     *
     * @return the value of tax.ENDDATE
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.ENDDATE
     *
     * @param enddate the value for tax.ENDDATE
     *
     * @mbg.generated Sat Jan 18 18:25:39 JST 2020
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
}